// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// logit
arma::vec logit(const arma::mat& X, const arma::vec& beta);
RcppExport SEXP milr_logit(SEXP XSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    __result = Rcpp::wrap(logit(X, beta));
    return __result;
END_RCPP
}
// CLR_lasso
arma::vec CLR_lasso(const arma::vec& Z, const arma::mat& X, const arma::vec& ID_dbl, const arma::vec& init_beta, const double& lambda, double alpha, double maxit);
RcppExport SEXP milr_CLR_lasso(SEXP ZSEXP, SEXP XSEXP, SEXP ID_dblSEXP, SEXP init_betaSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ID_dbl(ID_dblSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type init_beta(init_betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type maxit(maxitSEXP);
    __result = Rcpp::wrap(CLR_lasso(Z, X, ID_dbl, init_beta, lambda, alpha, maxit));
    return __result;
END_RCPP
}
