# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' logit link function
#'
#' calculate the values of logit link
#' 
#' @param X A matrix, the design matrix.
#' @param beta A vector, the coefficients.
#' @return An vector of the values of logit link.
#' @examples
#' logit(matrix(c(1, 0.5, -0.2, 0.3), 2), c(-0.5, -3)) # 0.5249792, 0.2404891
#' @export
logit <- function(X, beta) {
    .Call('milr_logit', PACKAGE = 'milr', X, beta)
}

CLR_lasso <- function(Z, X, ID_dbl, init_beta, lambda, alpha = 1, maxit = 500) {
    .Call('milr_CLR_lasso', PACKAGE = 'milr', Z, X, ID_dbl, init_beta, lambda, alpha, maxit)
}

softmaxlogL <- function(bag, instance, label_bag, beta, alpha) {
    .Call('milr_softmaxlogL', PACKAGE = 'milr', bag, instance, label_bag, beta, alpha)
}

